theme = "hugo-xmin"
baseURL = "http://jinli.link/"
languageCode = "en-us"
title = "JIN Li"
relativeURLs = true
enableEmoji = true
hasCJKLanguage = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[social]
    github  = "https://github.com/JIN-Li-stats"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
#[[menu.main]]
#    name = "About"
#    url = "/about/"
#    weight = 2
[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 3
[[menu.main]]
    name = "Note"
    url = "/note/"
    weight = 4
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 5
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "金力的博客"
    footer = "&copy; [JIN Li](https://jinli.link) 2020"
    
[permalinks]
  note= "/note/:year/:month/:day/:title/"
  post= "/post/:year/:month/:day/:title/"