theme = "hugo-xmin"
baseURL = "http://jinli.link/"
languageCode = "zh-cn"
title = "JIN Li"
relativeURLs = true
enableEmoji = true
googleAnalytics = "UA-1988641-2"
hasCJKLanguage = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
disqusShortname = "jinli-link"

[social]
    github  = "https://github.com/JIN-Li-stats"

[[menu.main]]
    name = "主页"
    url = "/"
    weight = 1
[[menu.main]]
    name = "博客"
    url = "/blog/"
    weight = 2
[[menu.main]]
    name = "分类"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 4
[[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 5
[[menu.main]]
    name = "订阅"
    url = "/index.xml"

[params]
    description = "金力的博客"
    footer = "&copy; [JIN Li](https://jinli.link) 2020-2022"
    
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"
    
[permalinks]
  note= "/note/:year/:month/:day/:title/"
  post= "/post/:year/:month/:day/:title/"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
