theme = "hugo-xmin"
baseURL = "http://example.org/"
languageCode = "en-us"
title = "Jin Li"

[social]
    github  = "https://github.com/JIN-Li-stats"


[[menu.main]]
    name = "Blog"
    url = "/blog/"

[[menu.main]]
    name = "Categories"
    url = "/categories/"

[[menu.main]]
    name = "About"
    url = "/about/"